# Generated by Django 2.2.3 on 2019-07-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
